# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraint1.xdc

# IP: ip/Rom_A/Rom_A.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Rom_A || ORIG_REF_NAME==Rom_A} -quiet] -quiet
